- hosts: apache
  remote_user: ec2-user
  become: yes
  tasks:
  - name: install httpd server
    yum :
      name: httpd
      state: latest 

  - name: Start service httpd, if not running
    service:
      name: httpd
      state: started

  - name: Start service httpd, if not running
    copy:
      src: /home/ec2-user/index.html
      dest: /var/www/html/index.html
      mode: '777'

  "userdata": "dinesh"
  "password": "dinesh123"
